//
//  CustomVC.swift
//  Dental Care
//
//  Created by Sanju Mohamed Sageer on 31/10/2022.
//

import UIKit

class CustomVC: UIViewController,UITableViewDelegate,UITableViewDataSource {
   
    
    var Pageid:String?
    var model:CustomModel?
    var privacypolicy:Bool?
    var delegate:profiledelegate?
    var headar = ["Our Privacy Policy","Definitions For the purposes of this Privacy Policy:","Collecting and Using Your Personal Data Types of Data Collected","Security of Your Personal Data","What Information Do We Collect?","How is Information Collected?","How Do We Use Your Personal Data?","Data Security","Data Retention","How to Access your Information"]
    var answerar = ["This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Template. Interpretation and Definitions Interpretation The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.","Account means a unique account created for You to access our Service or parts of our Service. Company (referred to as either the Company We Us or Our in this Agreement) refers to Appolonia Dentistry for Childern, Villa 4 - Plot 88 Theyab Bin Eissa St - Khalifa CitySE-5 - Abu Dhabi - United Arab Emirates.Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses. Country refers to: United Arab Emirates Device means any device that can access the Service such as a computer, a cellphone or a digital tablet. Personal Data is any information that relates to an identified or identifiable individual. Service refers to the Website. Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used. Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit). Website refers to Appolonia Dentistry for Childern, accessible from https://appolonia.ae/ You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.","While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: First name and last name Phone number Usage Data Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data. We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.","The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security. Links to Other Websites Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services. Changes to this Privacy Policy We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the Last updated date at the top of this Privacy Policy.","Each time you provide or transmit information to us via the Site or App, we may obtain and collect personally identifiable information about you, including, but not limited to, your face photos, your teeth photos, your name, email address, and any other information that may be used to identify you. We may also collect information about your IP address, browser type, cookie identifiers, Internet Service Provider, referring and exit page, operating system, clickstream data, the type of mobile device you use, and your mobile device's unique device ID.","Each time you provide or transmit information to us via the Site or App using , we may obtain and collect information about you, including, but not limited to, your name, email address, and any other information that may be used to identify you. For example, and without limitation, we may collect such information from you when you create a user account on the Site or App or when you contact our support team. If you are a patient, we may collect your Face Photos, Teeth Photos & other information required by the Doctor like previous medical history or allergies etc. to understand the real issue and prescribe the treatment plan for your problems. This information is collected using phone camera & via chat module where you interact with the Doctors or Clinic Customer Care.","We may use the information we collect from and about you for any of the following business purposes: (1) to fulfill your requests for prescribing treatment for your problems; (2) to respond to your inquiries; (3) to review Site or App usage and operations; (4) to address problems with the Site or App, our business, or our services; (5) to protect the security or integrity of the Site or App and our business; (6) to monitor the Site and App for compliance with our Terms of Use and the law; (7) to help improve our Site, App, or services; (8) to register and maintain an online or offline account; (9) to analyze how the Sites and App are used, to prepare aggregated trend reports, and to perform other market research; (10) to facilitate your interaction through the App with other users, including social networking; (11) to operate, analyze and enhance the performance and functioning of our Site and App and other products and services; and (12) to contact you with updates and other informational and promotional materials from us or third party marketing offers from our trusted partners, as well as from other companies. We never share your personal information with any third party & remains confidential with us.","We maintain reasonable and appropriate measures designed to maintain information we collect in a secure manner. We have taken certain physical, electronic, and administrative steps to safeguard and secure the information we collect from Site visitors and App users. Even though we follow reasonable procedures to try to protect the information in our possession, no security system is perfect and we cannot promise, and you should not expect, that your information will be secure in all circumstances.","We will only retain your personal data for as long as necessary to fulfill the purposes we collected it for, including for the purposes of satisfying any legal, accounting, or reporting requirements. To determine the appropriate retention period for personal data, we consider the amount, nature, and sensitivity of the personal data, the potential risk of harm from unauthorized use or disclosure of your personal data, the purposes for which we process your personal data and whether we can achieve those purposes through other means, and the applicable legal requirements.","If you would like to access, update, or delete any information we have about you, or exercise any right you might have, please use the Delete Account option within the app or contact us at itsupport@appolonia.ae"]
//    @IBOutlet weak var customHeader: UILabel!
//    @IBOutlet weak var customLabel: UILabel!
    override func viewDidLoad() {
        super.viewDidLoad()
//custompage()
      //  if privacypolicy == false {
          //  custompage()
            
      //  }else {
           //customHeader.text = "Privacy Policy"
       // }
   // customLabel.textColor = UIColor.white
        
    }
    @IBAction func backButtonAction(_ sender: UIButton) {
        delegate?.tabbar()
        navigationController?.popViewController(animated: true)
    }
//    func  viewloadinitiated() {
//        customHeader.text = model?.page.title ?? ""
//        customLabel.text = model?.page.description ?? ""
//        customLabel.textColor = UIColor.white
//    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return headar.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "privacyTVC") as! privacyTVC
        cell.customHeader.text = headar[indexPath.row]
        cell.customLabel.text = answerar[indexPath.row]
        return cell
    }


}
class privacyTVC:UITableViewCell {
    @IBOutlet weak var customHeader: UILabel!
    @IBOutlet weak var customLabel: UILabel!
}
